name: PHP Tests

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  themecheck:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.wp-content
          key: ${{ runner.os }}-wpcore
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      - name: Make run-theme-check executable
        run: chmod +x ./bin/run-theme-check.sh
      - name: Make install-theme-check executable
        run: chmod +x ./bin/install-theme-check.sh
      - run: ./bin/run-theme-check.sh

